import type {
  AnyTableDefinition,
  FitBaseType,
  FitDeveloperField,
  FitMessage,
  HealthMetricDefinition,
  HealthRepresentationDefinition,
  ProjectionDefinition,
  ProjectionName,
} from './types';

export const EXPORT_PAGE_MAX_ROWS = 4096;
export const EXPORT_PAGE_MAX_BYTES = 4 * 1024 * 1024;

const ALL = ['ios', 'android', 'web'] as const;
const PHONES = ['ios', 'android'] as const;
const CAPTURED = ['android', 'web'] as const;
const IOS = ['ios'] as const;
const ANDROID = ['android'] as const;
const WEB = ['web'] as const;
const SEGMENTED = ['ios', 'web'] as const;
const ZIP = ['zip'] as const;
const FIT = ['fit'] as const;
const BOTH = ['zip', 'fit'] as const;
const DISCOVERY = ['discovery'] as const;
const FIT_DISCOVERY = ['discovery', 'fit'] as const;

export const PROJECTIONS = {
  telemetry: {
    kinds: BOTH,
    columns: [
      { name: 'elapsedSeconds', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'timestamp', type: 'string', platforms: ALL, consumers: ZIP },
      { name: 'producerSequence', type: 'number', platforms: IOS, consumers: BOTH },
      { name: 'clockEpoch', type: 'string', platforms: IOS, consumers: BOTH },
      { name: 'active', type: 'number', platforms: CAPTURED, consumers: BOTH },
      { name: 'interval', type: 'number', platforms: WEB, consumers: BOTH },
      { name: 'connection', type: 'string', platforms: ALL, consumers: BOTH },
      { name: 'humanPowerW', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'cadenceRpm', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'motorInputPowerW', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'batteryVoltageV', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'batteryCurrentA', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'motorCurrentA', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'motorRpm', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'pedalTorqueNm', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'controllerTempC', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'motorTempC', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'consumedAh', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'consumedWh', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'throttleVoltageV', type: 'number', platforms: ALL, consumers: ZIP },
      { name: 'faultCode', type: 'number', platforms: ALL, consumers: ZIP },
      { name: 'assistLevel', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'controllerSpeedMps', type: 'number', platforms: ALL, consumers: ZIP },
      { name: 'raceMode', type: 'number', platforms: ALL, consumers: ZIP },
      { name: 'speedRaw', type: 'number', platforms: ALL, consumers: ZIP },
    ],
  },
  gps: {
    kinds: BOTH,
    columns: [
      { name: 'elapsedSeconds', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'timestamp', type: 'string', platforms: PHONES, consumers: ZIP },
      { name: 'producer', type: 'string', platforms: PHONES, consumers: BOTH },
      { name: 'producerSequence', type: 'number', platforms: IOS, consumers: BOTH },
      { name: 'clockEpoch', type: 'string', platforms: IOS, consumers: BOTH },
      { name: 'active', type: 'number', platforms: ANDROID, consumers: BOTH },
      { name: 'latitude', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'longitude', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'altitudeMeters', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'verticalAccuracyM', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'ellipsoidalAltitudeMeters', type: 'number', platforms: ANDROID, consumers: ZIP },
      { name: 'ellipsoidalVerticalAccuracyM', type: 'number', platforms: ANDROID, consumers: ZIP },
      { name: 'horizontalAccuracyM', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'speedMps', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'speedAccuracyMps', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'courseDegrees', type: 'number', platforms: PHONES, consumers: ZIP },
      { name: 'courseAccuracyDegrees', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'distanceBarrier', type: 'number', platforms: IOS, consumers: BOTH },
    ],
  },
  gpsDiscovery: {
    kinds: FIT,
    columns: [
      { name: 'elapsedSeconds', type: 'number', platforms: PHONES, consumers: DISCOVERY },
      { name: 'timestamp', type: 'string', platforms: ANDROID, consumers: DISCOVERY },
      { name: 'active', type: 'number', platforms: ANDROID, consumers: DISCOVERY },
      { name: 'producer', type: 'string', platforms: PHONES, consumers: DISCOVERY },
      { name: 'horizontalAccuracyM', type: 'number', platforms: PHONES, consumers: DISCOVERY },
    ],
  },
  healthZip: {
    kinds: ZIP,
    columns: [
      { name: 'elapsedSeconds', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'timestamp', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'producer', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'producerSequence', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'clockEpoch', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'heartRateBpm', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'activeEnergyKcal', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'basalEnergyKcal', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'distanceMeters', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'riderPowerW', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'cadenceRpm', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'speedMps', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'identifier', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'value', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'unit', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'representation', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'sampleCount', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'sampleStart', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'sampleUUID', type: 'string', platforms: IOS, consumers: ZIP },
      { name: 'sourceBundleIdentifier', type: 'string', platforms: IOS, consumers: ZIP },
    ],
  },
  healthFit: {
    kinds: FIT,
    columns: [
      { name: 'elapsedSeconds', type: 'number', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'producer', type: 'string', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'producerSequence', type: 'number', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'clockEpoch', type: 'string', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'connectionEpoch', type: 'string', platforms: IOS, consumers: FIT },
      { name: 'representation', type: 'string', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'sampleCount', type: 'number', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'heartRateBpm', type: 'number', platforms: IOS, consumers: FIT_DISCOVERY },
      { name: 'activeEnergyKcal', type: 'number', platforms: IOS, consumers: FIT_DISCOVERY },
    ],
  },
  lifecycle: {
    kinds: BOTH,
    columns: [
      { name: 'elapsedSeconds', type: 'number', platforms: ALL, consumers: BOTH },
      { name: 'timestamp', type: 'string', platforms: ALL, consumers: ZIP },
      { name: 'producer', type: 'string', platforms: ALL, consumers: BOTH },
      { name: 'producerSequence', type: 'number', platforms: IOS, consumers: BOTH },
      { name: 'clockEpoch', type: 'string', platforms: IOS, consumers: BOTH },
      { name: 'action', type: 'string', platforms: ALL, consumers: BOTH },
      { name: 'timerSeconds', type: 'number', platforms: IOS, consumers: ZIP },
      { name: 'interrupted', type: 'number', platforms: PHONES, consumers: BOTH },
      { name: 'cycSequence', type: 'number', platforms: IOS, consumers: BOTH },
    ],
  },
  distance: {
    kinds: FIT,
    columns: [
      { name: 'start', type: 'number', platforms: ALL, consumers: FIT },
      { name: 'end', type: 'number', platforms: ALL, consumers: FIT },
      { name: 'meters', type: 'number', platforms: ALL, consumers: FIT },
      { name: 'segment', type: 'number', platforms: SEGMENTED, consumers: FIT },
      { name: 'startSpeed', type: 'number', platforms: ALL, consumers: FIT },
      { name: 'endSpeed', type: 'number', platforms: ALL, consumers: FIT },
    ],
  },
} as const satisfies Record<ProjectionName, ProjectionDefinition>;

const TIMELINE = ['elapsedSeconds', 'producerSequence', 'clockEpoch', 'active', 'interval'] as const;
const GPS_TIMELINE = ['elapsedSeconds', 'producer', 'producerSequence', 'clockEpoch', 'active'] as const;
const HEALTH_TIMELINE = ['elapsedSeconds', 'producer', 'producerSequence', 'clockEpoch'] as const;
const HEALTH_VALUE_KEYS = [
  'heartRateBpm',
  'activeEnergyKcal',
  'basalEnergyKcal',
  'distanceMeters',
  'riderPowerW',
  'cadenceRpm',
  'speedMps',
] as const;

export const TABLES = [
  {
    name: 'telemetry',
    path: 'telemetry.csv',
    projection: 'telemetry',
    fields: [
      {
        name: 'timestamp',
        type: 'datetime',
        description: 'Original reading time in the source clock, as retained',
        reads: ['timestamp'],
      },
      {
        name: 'elapsedSeconds',
        type: 'number',
        description: 'Time on the ride timeline',
        'powerLog:unit': 's',
        reads: ['elapsedSeconds'],
      },
      {
        name: 'activeInterval',
        type: 'integer',
        description: 'Activity interval, numbered from 1; empty while paused',
        reads: TIMELINE,
      },
      {
        name: 'run',
        type: 'integer',
        description: 'Continuous run of readings, numbered from 1 in order of first appearance',
        reads: [...TIMELINE, 'connection'],
      },
      {
        name: 'connection',
        type: 'integer',
        description: 'Controller connection, numbered as in powerLog:sources.connections',
        reads: ['connection'],
      },
      {
        name: 'humanPowerW',
        type: 'number',
        description: 'Rider power reported by the controller',
        'powerLog:unit': 'W',
        reads: ['humanPowerW'],
      },
      {
        name: 'cadenceRpm',
        type: 'number',
        description: 'Crank cadence reported by the controller, smoothed',
        'powerLog:unit': '/min',
        reads: ['cadenceRpm'],
      },
      {
        name: 'motorInputPowerW',
        type: 'number',
        description: 'Battery input power: battery voltage × battery current; not motor output or rider power',
        'powerLog:unit': 'W',
        reads: ['motorInputPowerW'],
      },
      {
        name: 'batteryVoltageV',
        type: 'number',
        description: 'Battery voltage',
        'powerLog:unit': 'V',
        reads: ['batteryVoltageV'],
      },
      {
        name: 'batteryCurrentA',
        type: 'number',
        description: 'Battery current; negative under regeneration',
        'powerLog:unit': 'A',
        reads: ['batteryCurrentA'],
      },
      {
        name: 'motorCurrentA',
        type: 'number',
        description: 'Motor current',
        'powerLog:unit': 'A',
        reads: ['motorCurrentA'],
      },
      {
        name: 'motorRpm',
        type: 'number',
        description: 'Motor speed; not crank cadence',
        'powerLog:unit': '/min',
        reads: ['motorRpm'],
      },
      {
        name: 'pedalTorqueNm',
        type: 'number',
        description: 'Pedal torque',
        'powerLog:unit': 'N.m',
        reads: ['pedalTorqueNm'],
      },
      {
        name: 'controllerTempC',
        type: 'number',
        description: 'Controller temperature; not ambient temperature',
        'powerLog:unit': 'Cel',
        reads: ['controllerTempC'],
      },
      {
        name: 'motorTempC',
        type: 'number',
        description: 'Motor temperature; not ambient temperature',
        'powerLog:unit': 'Cel',
        reads: ['motorTempC'],
      },
      {
        name: 'consumedAh',
        type: 'number',
        description: 'Charge counter of the controller; not ride consumption',
        'powerLog:unit': 'A.h',
        reads: ['consumedAh'],
      },
      {
        name: 'consumedWh',
        type: 'number',
        description: 'Energy counter of the controller; not ride consumption',
        'powerLog:unit': 'W.h',
        reads: ['consumedWh'],
      },
      {
        name: 'throttleVoltageV',
        type: 'number',
        description: 'Throttle voltage',
        'powerLog:unit': 'V',
        reads: ['throttleVoltageV'],
      },
      {
        name: 'faultCode',
        type: 'integer',
        description: "Fault code in the vocabulary of the connection's vendor",
        reads: ['faultCode'],
      },
      {
        name: 'assistLevel',
        type: 'integer',
        description: 'Assist level reported by the controller',
        reads: ['assistLevel'],
      },
      {
        name: 'controllerSpeedMps',
        type: 'number',
        description: 'Controller speed, normalized for a known controller profile',
        'powerLog:unit': 'm/s',
        reads: ['controllerSpeedMps'],
      },
      {
        name: 'cyc.raceMode',
        type: 'integer',
        description: 'CYC race mode',
        'powerLog:vendor': 'cyc',
        reads: ['raceMode'],
      },
      {
        name: 'cyc.speedRaw',
        type: 'number',
        description: 'CYC speed field divided by 100; its unit depends on the controller profile',
        'powerLog:vendor': 'cyc',
        reads: ['speedRaw'],
      },
    ],
  },
  {
    name: 'gps',
    path: 'gps.csv',
    projection: 'gps',
    fields: [
      {
        name: 'timestamp',
        type: 'datetime',
        description: 'Original fix time in the source clock, as retained',
        reads: ['timestamp'],
      },
      {
        name: 'elapsedSeconds',
        type: 'number',
        description: 'Time on the ride timeline',
        'powerLog:unit': 's',
        reads: ['elapsedSeconds'],
      },
      {
        name: 'activeInterval',
        type: 'integer',
        description: 'Activity interval, numbered from 1; empty while paused',
        reads: GPS_TIMELINE,
      },
      {
        name: 'run',
        type: 'integer',
        description:
          'Continuous run of fixes, numbered from 1 in order of first appearance; a barrier fix is its own run',
        reads: [...GPS_TIMELINE, 'distanceBarrier'],
      },
      {
        name: 'source',
        type: 'string',
        description: 'GPS producer: phone or watch',
        reads: ['producer'],
      },
      {
        name: 'latitude',
        type: 'number',
        description: 'Latitude',
        'powerLog:unit': 'deg',
        reads: ['latitude'],
      },
      {
        name: 'longitude',
        type: 'number',
        description: 'Longitude',
        'powerLog:unit': 'deg',
        reads: ['longitude'],
      },
      {
        name: 'altitudeMeters',
        type: 'number',
        description: 'Altitude above mean sea level',
        'powerLog:unit': 'm',
        reads: ['altitudeMeters'],
      },
      {
        name: 'verticalAccuracyM',
        type: 'number',
        description: 'Vertical accuracy of altitudeMeters',
        'powerLog:unit': 'm',
        reads: ['verticalAccuracyM'],
      },
      {
        name: 'ellipsoidalAltitudeMeters',
        type: 'number',
        description: 'Height above the WGS84 ellipsoid (Android)',
        'powerLog:unit': 'm',
        reads: ['ellipsoidalAltitudeMeters'],
      },
      {
        name: 'ellipsoidalVerticalAccuracyM',
        type: 'number',
        description: 'Vertical accuracy of ellipsoidalAltitudeMeters (Android)',
        'powerLog:unit': 'm',
        reads: ['ellipsoidalVerticalAccuracyM'],
      },
      {
        name: 'horizontalAccuracyM',
        type: 'number',
        description: 'Horizontal accuracy',
        'powerLog:unit': 'm',
        reads: ['horizontalAccuracyM'],
      },
      {
        name: 'speedMps',
        type: 'number',
        description: 'GPS speed',
        'powerLog:unit': 'm/s',
        reads: ['speedMps'],
      },
      {
        name: 'speedAccuracyMps',
        type: 'number',
        description: 'Accuracy of speedMps',
        'powerLog:unit': 'm/s',
        reads: ['speedAccuracyMps'],
      },
      {
        name: 'courseDegrees',
        type: 'number',
        description: 'Direction of travel; not device heading',
        'powerLog:unit': 'deg',
        reads: ['courseDegrees'],
      },
      {
        name: 'courseAccuracyDegrees',
        type: 'number',
        description: 'Accuracy of courseDegrees',
        'powerLog:unit': 'deg',
        reads: ['courseAccuracyDegrees'],
      },
    ],
  },
  {
    name: 'health',
    path: 'health.csv',
    projection: 'healthZip',
    fields: [
      {
        name: 'timestamp',
        type: 'datetime',
        description: 'Sample end, or the instant of an instantaneous value',
        reads: ['timestamp'],
      },
      {
        name: 'startTimestamp',
        type: 'datetime',
        description: 'Sample interval start; empty for instants',
        reads: ['sampleStart'],
      },
      {
        name: 'elapsedSeconds',
        type: 'number',
        description: 'Time on the ride timeline',
        'powerLog:unit': 's',
        reads: ['elapsedSeconds'],
      },
      {
        name: 'activeInterval',
        type: 'integer',
        description: 'Activity interval, numbered from 1; empty outside activity',
        reads: HEALTH_TIMELINE,
      },
      {
        name: 'source',
        type: 'string',
        description: 'Health producer: phone or watch',
        reads: ['producer'],
      },
      {
        name: 'sourceApp',
        type: 'string',
        description: 'Bundle identifier of the app that recorded the sample, when known',
        reads: ['sourceBundleIdentifier'],
      },
      {
        name: 'metric',
        type: 'string',
        description: 'Measured quantity',
        reads: [...HEALTH_VALUE_KEYS, 'identifier'],
      },
      {
        name: 'value',
        type: 'number',
        description: 'Measured value, in unit',
        reads: [...HEALTH_VALUE_KEYS, 'value'],
      },
      {
        name: 'unit',
        type: 'string',
        description: 'UCUM unit of value; an unknown metric keeps its stored unit, which is not UCUM',
        reads: ['identifier', 'unit'],
      },
      {
        name: 'kind',
        type: 'string',
        description: 'sample, aggregate, latest, cumulative or final',
        reads: ['representation', 'sampleCount'],
      },
      {
        name: 'sampleCount',
        type: 'integer',
        description: 'Number of values condensed into an aggregate',
        reads: ['sampleCount'],
      },
      {
        name: 'sampleId',
        type: 'string',
        description: "HealthKit sample UUID; series values carry their parent's",
        reads: ['sampleUUID'],
      },
    ],
  },
  {
    name: 'events',
    path: 'events.csv',
    projection: 'lifecycle',
    fields: [
      {
        name: 'timestamp',
        type: 'datetime',
        description: 'Original event time, as retained',
        reads: ['timestamp'],
      },
      {
        name: 'elapsedSeconds',
        type: 'number',
        description: 'Time on the ride timeline',
        'powerLog:unit': 's',
        reads: ['elapsedSeconds'],
      },
      {
        name: 'timerSeconds',
        type: 'number',
        description: 'Active time at the event; empty when not retained',
        'powerLog:unit': 's',
        reads: ['timerSeconds'],
      },
      {
        name: 'action',
        type: 'string',
        description: 'start, pause, resume, lap or stop',
        reads: ['action'],
      },
      {
        name: 'interrupted',
        type: 'boolean',
        description: 'The event records a capture interruption',
        reads: ['interrupted', 'action'],
      },
      {
        name: 'source',
        type: 'string',
        description: 'Recorder: phone, watch or browser',
        reads: ['producer'],
      },
    ],
  },
] as const satisfies readonly AnyTableDefinition[];

export const HEALTH_METRICS = [
  {
    metric: 'heartRate',
    key: 'heartRateBpm',
    identifier: 'HKQuantityTypeIdentifierHeartRate',
    unit: '/min',
    factor: 1,
    kindWithoutRepresentation: 'latest',
  },
  {
    metric: 'activeEnergy',
    key: 'activeEnergyKcal',
    identifier: 'HKQuantityTypeIdentifierActiveEnergyBurned',
    unit: 'kcal',
    factor: 1,
    kindWithoutRepresentation: 'cumulative',
  },
  {
    metric: 'basalEnergy',
    key: 'basalEnergyKcal',
    identifier: 'HKQuantityTypeIdentifierBasalEnergyBurned',
    unit: 'kcal',
    factor: 1,
    kindWithoutRepresentation: 'cumulative',
  },
  {
    metric: 'distance',
    key: 'distanceMeters',
    identifier: 'HKQuantityTypeIdentifierDistanceCycling',
    unit: 'm',
    factor: 1,
    kindWithoutRepresentation: 'cumulative',
  },
  {
    metric: 'power',
    key: 'riderPowerW',
    identifier: 'HKQuantityTypeIdentifierCyclingPower',
    unit: 'W',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'cadence',
    key: 'cadenceRpm',
    identifier: 'HKQuantityTypeIdentifierCyclingCadence',
    unit: '/min',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'speed',
    key: 'speedMps',
    identifier: 'HKQuantityTypeIdentifierCyclingSpeed',
    unit: 'm/s',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'respiratoryRate',
    key: null,
    identifier: 'HKQuantityTypeIdentifierRespiratoryRate',
    unit: '/min',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'oxygenSaturation',
    key: null,
    identifier: 'HKQuantityTypeIdentifierOxygenSaturation',
    unit: '%',
    factor: 100,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'heartRateVariabilitySDNN',
    key: null,
    identifier: 'HKQuantityTypeIdentifierHeartRateVariabilitySDNN',
    unit: 'ms',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'physicalEffort',
    key: null,
    identifier: 'HKQuantityTypeIdentifierPhysicalEffort',
    unit: 'kcal/(kg.h)',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'functionalThresholdPower',
    key: null,
    identifier: 'HKQuantityTypeIdentifierCyclingFunctionalThresholdPower',
    unit: 'W',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'workoutEffort',
    key: null,
    identifier: 'HKQuantityTypeIdentifierWorkoutEffortScore',
    unit: '{score}',
    factor: 1,
    kindWithoutRepresentation: null,
  },
  {
    metric: 'estimatedWorkoutEffort',
    key: null,
    identifier: 'HKQuantityTypeIdentifierEstimatedWorkoutEffortScore',
    unit: '{score}',
    factor: 1,
    kindWithoutRepresentation: null,
  },
] as const satisfies readonly HealthMetricDefinition[];

export const HEALTH_REPRESENTATIONS = {
  rawSeries: { kind: 'sample' },
  rawQuantity: { kind: 'sample', condensedKind: 'aggregate' },
  builderMostRecent: { kind: 'latest' },
  cumulativeWorkoutTotal: { kind: 'cumulative' },
  finalWorkoutTotal: { kind: 'final' },
  workoutAssociation: { kind: null },
  healthTombstone: { kind: null },
  workoutMetadata: { kind: null },
} as const satisfies Record<string, HealthRepresentationDefinition>;

export const FIT_BASE_TYPES = {
  enum: { code: 0x00, size: 1 },
  uint8: { code: 0x02, size: 1 },
  sint16: { code: 0x83, size: 2 },
  uint16: { code: 0x84, size: 2 },
  sint32: { code: 0x85, size: 4 },
  uint32: { code: 0x86, size: 4 },
  string: { code: 0x07, size: 1 },
  float32: { code: 0x88, size: 4 },
  byte: { code: 0x0d, size: 1 },
} as const satisfies Record<FitBaseType, { code: number; size: number }>;

export const FIT_MESSAGES = {
  fileId: {
    number: 0,
    fields: [
      { name: 'type', number: 0, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'manufacturer', number: 1, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'product', number: 2, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'time_created', number: 4, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
    ],
  },
  developerDataId: {
    number: 207,
    fields: [
      { name: 'application_id', number: 1, type: 'byte', code: 0x0d, size: 16, scale: 1, offset: 0 },
      { name: 'developer_data_index', number: 3, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
    ],
  },
  fieldDescription: {
    number: 206,
    fields: [
      { name: 'developer_data_index', number: 0, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'field_definition_number', number: 1, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'fit_base_type_id', number: 2, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'field_name', number: 3, type: 'string', code: 0x07, size: 23, scale: 1, offset: 0 },
      { name: 'units', number: 8, type: 'string', code: 0x07, size: 4, scale: 1, offset: 0 },
    ],
  },
  event: {
    number: 21,
    fields: [
      { name: 'timestamp', number: 253, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'event', number: 0, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'event_type', number: 1, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'data', number: 3, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
    ],
  },
  record: {
    number: 20,
    fields: [
      { name: 'timestamp', number: 253, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'position_lat', number: 0, type: 'sint32', code: 0x85, size: 4, scale: 1, offset: 0 },
      { name: 'position_long', number: 1, type: 'sint32', code: 0x85, size: 4, scale: 1, offset: 0 },
      { name: 'enhanced_altitude', number: 78, type: 'uint32', code: 0x86, size: 4, scale: 5, offset: 500 },
      { name: 'enhanced_speed', number: 73, type: 'uint32', code: 0x86, size: 4, scale: 1000, offset: 0 },
      { name: 'distance', number: 5, type: 'uint32', code: 0x86, size: 4, scale: 100, offset: 0 },
      { name: 'heart_rate', number: 3, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'power', number: 7, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'cadence', number: 4, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'motor_power', number: 82, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'ebike_assist_mode', number: 119, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
    ],
  },
  lap: {
    number: 19,
    fields: [
      { name: 'timestamp', number: 253, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'message_index', number: 254, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'event', number: 0, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'event_type', number: 1, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'start_time', number: 2, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'total_elapsed_time', number: 7, type: 'uint32', code: 0x86, size: 4, scale: 1000, offset: 0 },
      { name: 'total_timer_time', number: 8, type: 'uint32', code: 0x86, size: 4, scale: 1000, offset: 0 },
      { name: 'total_distance', number: 9, type: 'uint32', code: 0x86, size: 4, scale: 100, offset: 0 },
      { name: 'lap_trigger', number: 24, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'sport', number: 25, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
    ],
  },
  session: {
    number: 18,
    fields: [
      { name: 'timestamp', number: 253, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'message_index', number: 254, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'event', number: 0, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'event_type', number: 1, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'start_time', number: 2, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'sport', number: 5, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'sub_sport', number: 6, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'total_elapsed_time', number: 7, type: 'uint32', code: 0x86, size: 4, scale: 1000, offset: 0 },
      { name: 'total_timer_time', number: 8, type: 'uint32', code: 0x86, size: 4, scale: 1000, offset: 0 },
      { name: 'total_distance', number: 9, type: 'uint32', code: 0x86, size: 4, scale: 100, offset: 0 },
      { name: 'total_calories', number: 11, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'avg_speed', number: 14, type: 'uint16', code: 0x84, size: 2, scale: 1000, offset: 0 },
      { name: 'max_speed', number: 15, type: 'uint16', code: 0x84, size: 2, scale: 1000, offset: 0 },
      { name: 'avg_heart_rate', number: 16, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'max_heart_rate', number: 17, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'avg_cadence', number: 18, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'max_cadence', number: 19, type: 'uint8', code: 0x02, size: 1, scale: 1, offset: 0 },
      { name: 'avg_power', number: 20, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'max_power', number: 21, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'total_ascent', number: 22, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'total_descent', number: 23, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'first_lap_index', number: 25, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'num_laps', number: 26, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'total_work', number: 48, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'avg_lev_motor_power', number: 129, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'max_lev_motor_power', number: 130, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
    ],
  },
  activity: {
    number: 34,
    fields: [
      { name: 'timestamp', number: 253, type: 'uint32', code: 0x86, size: 4, scale: 1, offset: 0 },
      { name: 'total_timer_time', number: 0, type: 'uint32', code: 0x86, size: 4, scale: 1000, offset: 0 },
      { name: 'num_sessions', number: 1, type: 'uint16', code: 0x84, size: 2, scale: 1, offset: 0 },
      { name: 'type', number: 2, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'event', number: 3, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
      { name: 'event_type', number: 4, type: 'enum', code: 0x00, size: 1, scale: 1, offset: 0 },
    ],
  },
} as const satisfies Record<string, FitMessage>;

export const FIT_DEVELOPER_APPLICATION_ID = '9b716e18-08fe-4c23-b64f-be64d517cb48';
export const FIT_DEVELOPER_DATA_INDEX = 0;

export const FIT_DEVELOPER_FIELDS = [
  {
    number: 0,
    name: 'battery_power',
    type: 'sint16',
    code: 0x83,
    units: 'W',
    policy: 'mean',
    channel: 'motorInputPowerW',
  },
  {
    number: 1,
    name: 'battery_voltage',
    type: 'float32',
    code: 0x88,
    units: 'V',
    policy: 'mean',
    channel: 'batteryVoltageV',
  },
  {
    number: 2,
    name: 'battery_current',
    type: 'float32',
    code: 0x88,
    units: 'A',
    policy: 'mean',
    channel: 'batteryCurrentA',
  },
  {
    number: 3,
    name: 'motor_current',
    type: 'float32',
    code: 0x88,
    units: 'A',
    policy: 'mean',
    channel: 'motorCurrentA',
  },
  { number: 4, name: 'motor_speed', type: 'float32', code: 0x88, units: 'rpm', policy: 'mean', channel: 'motorRpm' },
  {
    number: 5,
    name: 'motor_temperature',
    type: 'sint16',
    code: 0x83,
    units: 'C',
    policy: 'mean',
    channel: 'motorTempC',
  },
  {
    number: 6,
    name: 'controller_temperature',
    type: 'sint16',
    code: 0x83,
    units: 'C',
    policy: 'mean',
    channel: 'controllerTempC',
  },
  {
    number: 7,
    name: 'pedal_torque',
    type: 'float32',
    code: 0x88,
    units: 'Nm',
    policy: 'mean',
    channel: 'pedalTorqueNm',
  },
  {
    number: 8,
    name: 'consumed_energy',
    type: 'float32',
    code: 0x88,
    units: 'Wh',
    policy: 'last',
    channel: 'consumedWh',
  },
  {
    number: 9,
    name: 'consumed_charge',
    type: 'float32',
    code: 0x88,
    units: 'Ah',
    policy: 'last',
    channel: 'consumedAh',
  },
] as const satisfies readonly FitDeveloperField[];
