import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';

export function filesIn(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const file = join(directory, entry.name);
    return entry.isDirectory() ? filesIn(file) : [file];
  });
}

const licenseName = /^(licen[sc]e|copying|notice)(\..*)?$/i;
const licenseFiles = directory =>
  readdirSync(directory)
    .filter(name => licenseName.test(name) && statSync(join(directory, name)).isFile())
    .sort();
const licenseExpression = metadata =>
  typeof metadata.license === 'string'
    ? metadata.license
    : (metadata.license?.type ??
      (Array.isArray(metadata.licenses) ? metadata.licenses.map(item => item.type ?? item).join(' OR ') : null));

export function generateWebNotices(root, exportDirectory) {
  const packages = new Map();
  const exportFiles = filesIn(exportDirectory);

  function record(source, content = '') {
    const index = source.indexOf('node_modules/');
    if (index < 0) return;
    const local = source.slice(index);
    const segments = local.split('/');
    const moduleIndex = segments.lastIndexOf('node_modules');
    const scope = segments[moduleIndex + 1];
    if (!scope) return;
    const packagePath = segments.slice(0, moduleIndex + (scope.startsWith('@') ? 3 : 2)).join('/');
    const directory = resolve(root, packagePath);
    if (!directory.startsWith(resolve(root) + sep)) throw new Error(`Bundled source outside the project: ${source}`);
    if (!existsSync(join(directory, 'package.json'))) return;
    let entry = packages.get(packagePath);
    if (!entry) {
      const metadata = JSON.parse(readFileSync(join(directory, 'package.json'), 'utf8'));
      const own = licenseFiles(directory);
      entry = {
        name: metadata.name ?? packagePath,
        version: metadata.version ?? '',
        license: licenseExpression(metadata),
        ownLicense: own.length > 0,
        documents: new Map(),
        headers: new Set(),
      };
      for (const name of own) entry.documents.set(name, readFileSync(join(directory, name), 'utf8'));
      packages.set(packagePath, entry);
    }
    // Vendored code keeps its own licence in a subdirectory below the package root.
    for (let cursor = dirname(resolve(root, local)); cursor.startsWith(directory + sep); cursor = dirname(cursor)) {
      if (!existsSync(cursor)) continue;
      for (const name of licenseFiles(cursor))
        entry.documents.set(join(relative(directory, cursor), name), readFileSync(join(cursor, name), 'utf8'));
    }
    // Original sources still carry the notices that minification strips from the bundle.
    for (const comment of content.match(/\/\*[\s\S]*?\*\/|^[ \t]*\/\/[^\n]*/gm) ?? []) {
      if (/copyright|@license\b/i.test(comment)) entry.headers.add(comment.trim());
    }
  }

  for (const file of exportFiles.filter(file => file.endsWith('.js.map'))) {
    const map = JSON.parse(readFileSync(file, 'utf8'));
    (map.sources ?? []).forEach((source, position) => record(source, map.sourcesContent?.[position] ?? ''));
  }
  for (const file of exportFiles) record(relative(exportDirectory, file).split(sep).join('/'));

  const entries = [...packages.values()].sort((a, b) =>
    `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`, 'en'),
  );
  const label = entry => `${entry.name}@${entry.version}`;
  const missingLicenseFile = entries.filter(entry => !entry.ownLicense).map(label);
  const missingCopyright = entries.filter(entry => !entry.ownLicense && entry.headers.size === 0).map(label);
  const sections = entries.map(entry =>
    [
      `${label(entry)} — ${entry.license ?? 'no licence declared in package.json'}`,
      ...(entry.ownLicense
        ? []
        : [
            `This package publishes no licence file of its own. Its declared licence is ${entry.license ?? 'not stated'}.`,
          ]),
      ...(!entry.ownLicense && entry.headers.size === 0
        ? ['No copyright notice was found in its bundled source.']
        : []),
      ...[...entry.documents].map(([name, text]) => `--- ${name} ---\n${text.trim()}`),
      ...(entry.headers.size
        ? [`--- Notices retained from bundled source ---\n${[...entry.headers].sort().join('\n\n')}`]
        : []),
    ].join('\n\n'),
  );
  const list = items => (items.length ? items.join(', ') : 'none');
  const divider = '\n\n' + '='.repeat(78) + '\n\n';
  const notices =
    [
      'Power Log — third-party notices for the compiled website',
      "Generated by scripts/web-notices.mjs from the production bundle's source maps and exported assets, so only code and assets that ship in this website are listed. Each package appears with its declared licence, the licence and notice files published in the package, and the copyright or @license notices found in its bundled source." +
        `\n\nPackages that publish no licence file of their own: ${list(missingLicenseFile)}.` +
        `\nPackages where no copyright notice was found either: ${list(missingCopyright)}.`,
      ...sections,
    ].join(divider) + '\n';
  writeFileSync(join(exportDirectory, 'THIRD_PARTY_NOTICES.txt'), notices);
  writeFileSync(join(exportDirectory, 'LICENSE.txt'), readFileSync(join(root, 'LICENSE'), 'utf8'));
  return { notices, packageCount: entries.length, missingLicenseFile, missingCopyright };
}

export function removeSourceMaps(exportDirectory) {
  return filesIn(exportDirectory)
    .filter(file => !file.endsWith('.map'))
    .map(file => {
      if (/\.(js|css)$/.test(file)) {
        const content = readFileSync(file, 'utf8')
          .replace(/^\s*\/\/[#@]\s*sourceMappingURL=.*$/gm, '')
          .replace(/\/\*[#@]\s*sourceMappingURL=[\s\S]*?\*\//g, '');
        writeFileSync(file, content);
      }
      return file;
    });
}
